---
abstract: 'PSGI middleware for server side include content'
author:
  - 'Jan Henning Thorsen C<< jhthorsen at cpan.org >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-SSI
no_index:
  directory:
    - inc
    - t
requires:
  File::Basename: 2.7
  HTTP::Date: 5.831
  HTTP::Message: 5.82
  HTTP::Request: 5.82
  HTTP::Response: 5.82
  POSIX: 1.1
  Plack: 0.98
  base: 2.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Plack-Middleware-SSI
  homepage: http://search.cpan.org/dist/Plack-Middleware-SSI
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/plack-middleware-ssi.git
version: 0.11
